name:                optimal-binary-accelerate
version:             1.0.0.0
github:              "JustinLovinger/optimal-binary-accelerate"
license:             MIT
author:              "Justin Lovinger"
maintainer:          "git@justinlovinger.com"
copyright:           "Justin Lovinger"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Convert binary vectors backed by Accelerate.
# category:            data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JustinLovinger/optimal-binary-accelerate#readme>

ghc-options:
  -Wall

dependencies:
  - accelerate >= 1.3 && < 2
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  optimal-binary-accelerate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - hspec
      - optimal-binary-accelerate
      - random >= 1.1
